---
language: node_js
node_js:
  - "7"

sudo: false

dist: trusty
addons:
  chrome: stable

cache:
  yarn: true

env:
  - EMBER_TRY_SCENARIO=ember-lts-without-fastboot
  - EMBER_TRY_SCENARIO=ember-latest-without-fastboot
  - EMBER_TRY_SCENARIO=ember-beta-without-fastboot
  - EMBER_TRY_SCENARIO=ember-lts-with-fastboot
  - EMBER_TRY_SCENARIO=ember-latest-with-fastboot
  - EMBER_TRY_SCENARIO=ember-beta-with-fastboot

matrix:
  fast_finish: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --no-lockfile

script:
  - yarn run lint
  # Usually, it’s ok to finish the test scenario without reverting
  # to the addon's original dependency state, skipping "cleanup".
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO --skip-cleanup
