---
language: node_js
node_js:
  - "7"

sudo: false

dist: trusty
addons:
  chrome: stable

cache:
  npm: true

env:
  - EMBER_TRY_SCENARIO=ember-lts-without-fastboot
  - EMBER_TRY_SCENARIO=ember-latest-without-fastboot
  - EMBER_TRY_SCENARIO=ember-beta-without-fastboot
  - EMBER_TRY_SCENARIO=ember-lts-with-fastboot
  - EMBER_TRY_SCENARIO=ember-latest-with-fastboot
  - EMBER_TRY_SCENARIO=ember-beta-with-fastboot

matrix:
  fast_finish: true

install:
  - npm install

script:
  - npm run lint
  # Usually, it’s ok to finish the test scenario without reverting
  # to the addon's original dependency state, skipping "cleanup".
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO --skip-cleanup
